### ISSUE TITLE
用您的示例，为何无法得到PoseLandmarks

### ISSUE THREAD

**Issue by liuwq1020** [GreenShadeZhang/WinUI-Tutorial-Code#1]
下载您的代码之后，发现缺少.tflite文件，之后再google下载了；但是运行示例程序，发现handsOutput.PoseLandmarks != null。
不知道是下载的文件不对，还是文件拷贝错了地方，请指教，谢谢！

**Comment by GreenShadeZhang** [comment]
你要下载hand_landmark_full.tflite
palm_detection_full.tflite
的模型放到图上位置
![image](https://github.com/GreenShadeZhang/WinUI-Tutorial-Code/assets/24240675/1f811f43-fe46-4410-9498-27bbc8498b30)

**Comment by liuwq1020** [comment]
谢谢您的回复，我试一下看看
















在 2023-07-21 15:10:45，"Gil Zhang" ***@***.***> 写道：

你要下载hand_landmark_full.tflite
palm_detection_full.tflite
的模型放到图上位置

**Comment by liuwq1020** [comment]
目前的情况依然让我困惑，文件名称是否需要修改呢？还是其他地方的参数需要修改？箭头位置的文件是直接下载之后的文件名称
















在 2023-07-21 15:10:45，"Gil Zhang" ***@***.***> 写道：

你要下载hand_landmark_full.tflite
palm_detection_full.tflite
的模型放到图上位置

**Comment by GreenShadeZhang** [comment]
名字要保证和图片上的一致，官方文档里有下载地址的，因为mediapipe官方模块是根据名称引用的模型。

**Comment by GreenShadeZhang** [comment]
不好意思 我看错了，我以为你用的是手部检测，我重新给你截图吧，或者你去这个项目里参考，https://github.com/maker-community/ElectronBot.DotNet

我已经将功能进行了整合。

![image](https://github.com/GreenShadeZhang/WinUI-Tutorial-Code/assets/24240675/f34bf4ec-a737-4338-b0bd-1104f70a2c51)

[WinUI（WASDK）使用MediaPipe检查人体姿态关键点](https://www.cnblogs.com/GreenShade/p/17552324.html)

**Comment by liuwq1020** [comment]
好的，非常感谢







在 2023-07-21 16:23:22，"Gil Zhang" ***@***.***> 写道：

不好意思 我看错了，我以为你用的是手部检测，我重新给你截图吧，或者你去这个项目里参考，https://github.com/maker-community/ElectronBot.DotNet

我已经将功能进行了整合。

WinUI（WASDK）使用MediaPipe检查人体姿态关键点
